global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'myapp'
    static_configs:
      - targets: ['myapp_container:8080']
        labels:
          service: 'myapp'

  - job_name: 'zipkin'
    metrics_path: /metrics
    static_configs:
      - targets: ['zipkin:9411']
        labels:
          service: 'zipkin'
